package com.mohit.mjetpack.utilities

enum class Routes {
    SPLASH, HOME, MJETPACK, TOP_BAR, BOTTOM_BAR, BADGES, BUTTONS, CARDS,
    CHECKBOX, CHIPS, DATE_PICKER, DIALOGS, DIVIDER, LISTS,
    MENUS, NAVIGATION_BOTTOM_BAR, NAVIGATION_DRAWER,
    NAVIGATION_RAIL, PROGRESS_INDICATORS, RADIO_BUTTONS,
    BOTTOM_SHEET, SLIDERS, SNACKBAR, SWITCH, TABS,
    TEXT_FIELDS, TIME_PICKERS, TOOLTIPS
}